export const DEFAULT_UI_APP = {
  palette:         true,
  toolbar:         true,
  import:          true,
  openTree:        true,
  export:          true,
  rtt:             true,
  rttHeader:       true,
  dataTable:       true,
  dataTableHeader: true,
  statusBar:       true,
  statusStats:     true,
  statusSelect:    true,
  statusMessage:   true,
  statusShare:     true,
  help:            true,
  about:           true,
  themeToggle:     true,
  brand:           true,
  borderWidth:     null,
  borderColor:     null,
  borderRadius:    null,
  backgroundColor: null,
  paddingTop:      null,
  paddingRight:    null,
  paddingBottom:   null,
  paddingLeft:     null,
  treePaddingTop:    '8',
  treePaddingRight:  '8',
  treePaddingBottom: '8',
  treePaddingLeft:   '8',
  legendPaddingTop:    8,
  legendPaddingRight:  8,
  legendPaddingBottom: 8,
  legendPaddingLeft:   null,
  tbFileOps:       true,
  tbAnnotations:   true,
  tbNodeInfo:      true,
  tbNavigation:    true,
  tbZoom:          true,
  tbOrder:         true,
  tbRotate:        true,
  tbReroot:        true,
  tbHideShow:      true,
  tbColour:        true,
  tbFilter:        true,
  tbPanels:        true,
  keyboard:        true,
  scrollBar:       true,
};

export const DEFAULT_UI_EMBED = {
  ...DEFAULT_UI_APP,
  import:      false,
  openTree:    false,
  rtt:         false,
  dataTable:   false,
  keyboard:    false,
  help:        false,
  about:       false,
  themeToggle: false,
  brand:       false,
};

export const DEFAULT_UI_EMBEDFRAME = {
  ...DEFAULT_UI_APP,
  import:    false,
  openTree:  false,
  rtt:       false,
  dataTable: false,
};
