/** Path to the bundled example tree, relative to the peartree/ directory.
 *  @deprecated Use EXAMPLE_DATASETS[0].path instead. */
export const EXAMPLE_TREE_PATH = 'data/ebov.tree';

/** Key used for the embedded settings block in saved NEXUS files: [peartree={...}] */
export const APP_SETTINGS_KEY = 'peartree';

export const NODE_TOOLTIP_FIELDS = [
  { key: '__divergence__',    label: 'Divergence',   onTips: true,  onNodes: true  },
  { key: '__age__',           label: 'Age',          onTips: true,  onNodes: true  },
  { key: '__cal_date__',      label: 'Date',         onTips: true,  onNodes: true  },
  { key: '__branch_length__', label: 'Branch',       onTips: true,  onNodes: true  },
  { key: '__tips_below__',    label: 'Tips below',   onTips: false, onNodes: true  },
];

export const EXAMPLE_DATASETS = [
  {
    title:       'Ebola virus (EBOV)',
    description: 'Phylogenetic tree from the 2014–2016 West Africa epidemic.',
    path:        'data/ebov.tree',
  },
  {
    title:       'SARS-CoV-2 (15K)',
    description: 'Large SARS-CoV-2 tree with ~15,000 sequences.',
    path:        'data/SARS-CoV-2_15K.tree',
  },
  {
    title:       'Variola virus (VARV)',
    description: 'Smallpox virus (variola) phylogeny.',
    path:        'data/VARV.tree',
  },
];

export const PEARTREE_BASE_URL = 'http://peartree.live/';

export const REQUIRED_THEME_KEYS = [
  'canvasBgColor',
  'branchColor', 'branchWidth', 'elbowRadius',
  'tipLabelFontSize', 'tipLabelColor',
  'tipLabelShapeColor',
  'tipShapeSize', 'tipShapeColor', 'tipShapeHaloSize', 'tipShapeBgColor',
  'nodeShapeSize', 'nodeShapeColor', 'nodeShapeHaloSize', 'nodeShapeBgColor',
  'branchShapeColor', 'branchShapeHaloColor', 'branchShape2Color', 'branchShape3Color', 'branchShape4Color',
  'nodeLabelFontSize', 'nodeLabelTypefaceKey', 'nodeLabelTypefaceStyle',
  'nodeLabelColor', 'nodeLabelSpacing',
  'branchLabelFontSize', 'branchLabelTypefaceKey', 'branchLabelTypefaceStyle',
  'branchLabelColor', 'branchLabelSpacing',
  'nodeBarsColor', 'nodeBarsWidth', 'nodeBarsFillOpacity', 'nodeBarsStrokeOpacity',
  'paintColour',
  'cladeHighlightFillOpacity', 'cladeHighlightStrokeOpacity', 'cladeHighlightStrokeWidth',
  'cladeHighlightColour',
  'collapsedCladeFontSize', 'collapsedCladeStrokeWidth', 'collapsedCladeStrokeOpacity',
  'collapsedCladeTypefaceKey', 'collapsedCladeTypefaceStyle',
  'legendTextColor', 'legendFontSize', 'legendTypefaceKey', 'legendTypefaceStyle',
  'axisColor', 'axisFontSize', 'axisTypefaceKey', 'axisTypefaceStyle', 'axisLineWidth',
  'rttRegressionStyle', 'rttRegressionColor', 'rttRegressionWidth',
  'rttResidBandColor', 'rttResidBandStyle', 'rttResidBandWidth', 'rttResidBandFillColor', 'rttResidBandFillOpacity',
  'rttStatsBgColor', 'rttStatsTextColor', 'rttStatsFontSize',
  'rttAxisColor', 'rttAxisFontSize', 'rttAxisLineWidth', 'rttAxisTypefaceKey', 'rttAxisTypefaceStyle',
  'typeface', 'typefaceStyle',
  'selectedLabelStyle',
  'selectedTipGrowthFactor', 'selectedTipFillColor', 'selectedTipMinSize',
  'selectedTipFillOpacity', 'selectedTipStrokeColor', 'selectedTipStrokeWidth', 'selectedTipStrokeOpacity',
  'selectedNodeGrowthFactor', 'selectedNodeFillColor', 'selectedNodeMinSize',
  'selectedNodeFillOpacity', 'selectedNodeStrokeColor', 'selectedNodeStrokeWidth', 'selectedNodeStrokeOpacity',
  'tipHoverGrowthFactor', 'tipHoverFillColor', 'tipHoverMinSize',
  'tipHoverFillOpacity', 'tipHoverStrokeColor', 'tipHoverStrokeWidth', 'tipHoverStrokeOpacity',
  'nodeHoverGrowthFactor', 'nodeHoverFillColor', 'nodeHoverMinSize',
  'nodeHoverFillOpacity', 'nodeHoverStrokeColor', 'nodeHoverStrokeWidth', 'nodeHoverStrokeOpacity',
];

export const DEFAULT_SETTINGS = {
  rootStemPct:    '1',
  axisSpacingTop: '2',
  rootStubLength: '10',
  introAnimation:  'x-then-y',
  tipLabelShow:    'name',
  tipLabelAlign:   'off',
  tipLabelSpacing: '3',
  tipLabelsExtra:  ['off', 'off', 'off'],
  tipLabelsExtraLayouts: ['append', 'append', 'append'],
  tipLabelShape:             'off',
  tipLabelShapeSize:         '50',
  tipLabelShapeMarginLeft:   '2',
  tipLabelShapeSpacing:      '3',
  tipLabelShapesExtra:         ['off', 'off', 'off', 'off', 'off', 'off', 'off', 'off', 'off'],
  tipLabelShapeExtraColourBys: ['user_colour', 'user_colour', 'user_colour', 'user_colour', 'user_colour', 'user_colour', 'user_colour', 'user_colour', 'user_colour'],
  nodeLabelAnnotation: '',
  nodeLabelPosition:   'right',
  branchLabelAnnotation: '',
  branchLabelPosition:   'above',
  branchShape:             'off',
  branchShapeHeightPct:    '50',
  branchShapeWidth:        '1',
  branchShapeAlign:        'center',
  branchShapeSpacing:      '3',
  branchShapeColor:        '#aaaaaa',
  branchShapeColourBy:     'user_colour',
  branchShapeCountBy:      '',
  branchShapeHalo:         '0',
  branchShapeHaloColor:    '#02292e',
  branchShapesFilter:      null,
  branchShapesExtra:         ['off', 'off', 'off'],
  branchShapesExtraColors:   ['#aaaaaa', '#aaaaaa', '#aaaaaa'],
  branchShapesExtraColourBys:['user_colour', 'user_colour', 'user_colour'],
  branchShapesExtraCountBys: ['', '', ''],
  nodeBarsEnabled:    'off',
  nodeBarsLine:       'off',
  nodeBarsRange:      'off',
  cladeHighlightLeftEdge:  'outlineNodes',
  cladeHighlightRightEdge: 'outlineTips',
  cladeHighlightPadding:   '4',
  cladeHighlightRadius:    '4',
  legendHeightPct: '100',
  legendSpacing: '0',
  legendDecimalPlaces: null,
  legendAnnotation2: '',
  legend2Position:   'right',
  legendHeightPct2:  '50',
  legendDecimalPlaces2: null,
  legendAnnotation3: '',
  legend3Position:   'right',
  legendHeightPct3:  '50',
  legendDecimalPlaces3: null,
  legendAnnotation4: '',
  legend4Position:   'right',
  legendHeightPct4:  '50',
  legendDecimalPlaces4: null,
  axisShow:             'forward',
  axisDateAnnotation:   '',
  axisDateFormat:       'yyyy-MM-dd',
  axisMajorInterval:    'auto',
  axisMinorInterval:    'off',
  axisMajorLabelFormat: 'partial',
  axisMinorLabelFormat: 'off',
  rttResidBandShow:     'residual',
  rttXOrigin:           'root',
  rttGridLines:         'off',
  rttAspectRatio:       'fit',
  rttDateFormat:        'yyyy-MM-dd',
  rttMajorInterval:     'auto',
  rttMinorInterval:     'off',
  rttMajorLabelFormat:  'partial',
  rttMinorLabelFormat:  'off',
  dataTableOpen:   false,
  dataTablePinned: false,
  rttOpen:         false,
  rttPinned:       false,
  rttPanelWidth:   null,
  paletteOpen:     false,
  palettePinned:   false,
  baseTheme:     'Monochrome',
  defaultTheme:  'ARTIC',
  selectedTheme: 'ARTIC',
  axisRangeTimeLeft:     '',
  axisRangeTimeRight:    '',
  axisRangeForwardLeft:  '0',
  axisRangeForwardRight: '',
  axisRangeReverseLeft:  '',
  axisRangeReverseRight: '0',
};

export const NON_PERSISTENT_SETTINGS = [
  'axisRangeTimeLeft',
  'axisRangeTimeRight',
  'axisRangeForwardLeft',
  'axisRangeForwardRight',
  'axisRangeReverseLeft',
  'axisRangeReverseRight',
  'rootStemPct',
  'axisSpacingTop',
  'rootStubLength',
  'introAnimation',
];
